In [ ]:
pip install numpy
import numpy as np

def cargar_datos(ruta_archivo):
    # Carga los datos del archivo CSV utilizando NumPy
    datos = np.genfromtxt(ruta_archivo, delimiter=',', skip_header=1)
    return datos

if __name__ == "__main__":
    ruta_archivo = r'C:\Users\ivanc\Desktop\2. Inversiones\Python_Clases\retail-sales-analysis\DATA\retail_sales_dataset.csv'
    datos = cargar_datos(ruta_archivo)
    print(datos)

[[   1.   nan   nan ...    3.   50.  150.]
 [   2.   nan   nan ...    2.  500. 1000.]
 [   3.   nan   nan ...    1.   30.   30.]
 ...
 [ 998.   nan   nan ...    4.   25.  100.]
 [ 999.   nan   nan ...    3.   50.  150.]
 [1000.   nan   nan ...    4.   30.  120.]]


In [3]:
# Pedimos los must
datos.shape # Shape

(1000, 9)

In [4]:
datos[:5] # Head

array([[   1.,   nan,   nan,   nan,   34.,   nan,    3.,   50.,  150.],
       [   2.,   nan,   nan,   nan,   26.,   nan,    2.,  500., 1000.],
       [   3.,   nan,   nan,   nan,   50.,   nan,    1.,   30.,   30.],
       [   4.,   nan,   nan,   nan,   37.,   nan,    1.,  500.,  500.],
       [   5.,   nan,   nan,   nan,   30.,   nan,    2.,   50.,  100.]])

In [5]:
datos[-5:] # Tail

array([[ 996.,   nan,   nan,   nan,   62.,   nan,    1.,   50.,   50.],
       [ 997.,   nan,   nan,   nan,   52.,   nan,    3.,   30.,   90.],
       [ 998.,   nan,   nan,   nan,   23.,   nan,    4.,   25.,  100.],
       [ 999.,   nan,   nan,   nan,   36.,   nan,    3.,   50.,  150.],
       [1000.,   nan,   nan,   nan,   47.,   nan,    4.,   30.,  120.]])

In [6]:
np.mean(datos) # Describe np.std(datos)

np.float64(nan)

In [7]:
np.std(datos)

np.float64(nan)

In [9]:
datos.dtype # Info

dtype('float64')

In [11]:
np.isnan(datos)

array([[False,  True,  True, ..., False, False, False],
       [False,  True,  True, ..., False, False, False],
       [False,  True,  True, ..., False, False, False],
       ...,
       [False,  True,  True, ..., False, False, False],
       [False,  True,  True, ..., False, False, False],
       [False,  True,  True, ..., False, False, False]], shape=(1000, 9))

In [12]:
# Propiedades y métodos

print(datos.shape)
print(datos.size)
print(datos.ndim)

(1000, 9)
9000
2


In [13]:
# Suma de todos los elementos
print(np.sum(datos)) 

nan


In [14]:
# Estadísticas básicas
print(np.mean(datos))  # Media (promedio)
print(np.median(datos))  # Mediana
print(np.std(datos))  # Desviación estándar
print(np.var(datos))  # Varianza

nan
nan
nan
nan


In [16]:
# Método 2: np.nan_to_num (más versátil, reemplaza nan por 0 por defecto)
Datos_ceros = np.nan_to_num(datos, nan=0.0)
Datos_ceros

array([[   1.,    0.,    0., ...,    3.,   50.,  150.],
       [   2.,    0.,    0., ...,    2.,  500., 1000.],
       [   3.,    0.,    0., ...,    1.,   30.,   30.],
       ...,
       [ 998.,    0.,    0., ...,    4.,   25.,  100.],
       [ 999.,    0.,    0., ...,    3.,   50.,  150.],
       [1000.,    0.,    0., ...,    4.,   30.,  120.]], shape=(1000, 9))

In [20]:
# Suma de todos los elementos
print(np.sum(Datos_ceros)) 

1180296.0


In [18]:
print(np.nansum(datos))

1180296.0


In [19]:
# Si ya hiciste esto:
datos[np.isnan(datos)] = 0
# Entonces esto ya no dará NaN:
print(np.sum(datos))

1180296.0
